### ISSUE TITLE
redesign

### ISSUE THREAD

**Issue by ghost** [Samuel-Amaro/Gerenciamento-Estoque#1]

**Comment by Samuel-Amaro** [comment]
Fique a vontade. Se quiser contribuir com um design para a plataforma web, seria de muita ajuda, estou pensando em refazer o projeto para a web, dai precisaria de um design para a web com um UX/UI bem minimalista e moderno e responsivo.

**Comment by Samuel-Amaro** [comment]
a minha ideia e que irei mudar a stack do projeto, pois meu foco mudou em relação ao java, hoje minha stack e entorno do JavaScript/TypeScript, dai eu vou construir um back-end para ser um API-FIRST.

Em relação ao design se você conseguir constrói-lo no figma com um design system, seria muito bom.

**Comment by Samuel-Amaro** [comment]
Irei mudar o nome do projeto também para **StockMaster**

aqui está a nova modelagem dos dados do DATABASE

![der-stockmaster](https://github.com/Samuel-Amaro/Gerenciamento-Estoque/assets/49981516/226c5463-3dcd-4a30-8a36-7fdcec5d633d)
